// Maps GUID -> public URL for legacy card images.
// The manifest is generated by scripts/generate-legacy-manifest.js (runs as
// prestart/prebuild) and lists files served from public/legacy/. Keeping the
// images out of the webpack module graph avoids loading 1+GB of assets into
// the dev server process. Foil masks live alongside the main image as
// "{GUID}_foil.png" and are exposed under the "{GUID}_FOIL" manifest key.
import manifest from '../data/legacy-manifest.json';

const PUBLIC_URL = process.env.PUBLIC_URL || '';

const resolve = (key) => {
  const rel = manifest[key];
  return rel ? `${PUBLIC_URL}/${rel}` : null;
};

const getLegacyImage = (guid) => {
  if (!guid) return null;
  return resolve(guid.toUpperCase());
};

export const getLegacyFoil = (guid) => {
  if (!guid) return null;
  return resolve(`${guid.toUpperCase()}_FOIL`);
};

export default getLegacyImage;
