// Maps GUID -> public URL for legacy card images.
// The manifest is generated by scripts/generate-legacy-manifest.js (runs as
// prestart/prebuild) and lists files served from public/legacy/. Keeping the
// images out of the webpack module graph avoids loading 1+GB of assets into
// the dev server process.
import manifest from '../data/legacy-manifest.json';

const PUBLIC_URL = process.env.PUBLIC_URL || '';

const getLegacyImage = (guid) => {
  if (!guid) return null;
  const rel = manifest[guid.toUpperCase()];
  return rel ? `${PUBLIC_URL}/${rel}` : null;
};

export default getLegacyImage;
